### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by epoyraz** [epoyraz/nextjs15boilerplate#3]
---
name: 🐋 Add Docker Support
about: Implement Docker configuration for development and production environments
labels: ['enhancement', 'docker', 'devops', 'infrastructure']
assignees: ''
priority: high
---

# Add Docker Support for Development and Production

## Overview
We need to implement Docker support to containerize our Next.js application for both development and production environments. This will ensure consistent deployment across different platforms and simplify our CI/CD pipeline.

## Current Problems
1. Inconsistent deployment environments
2. Complex setup process for new instances
3. Difficulty managing dependencies
4. Scaling challenges
5. Environment-specific bugs

#### Base Dockerfile
```dockerfile
# syntax=docker/dockerfile:1

# ---- Base Node ----
FROM node:20-alpine AS base
WORKDIR /app
# Add dependencies for node-gyp and other native modules
RUN apk add --no-cache libc6-compat python3 make g++ 
ENV NODE_ENV=production

# ---- Dependencies ----
FROM base AS deps
# Copy package files
COPY package.json package-lock.json* ./
# Install dependencies
RUN npm ci

# ---- Build ----
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
# Build application
RUN npm run build

# ---- Production ----
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public

# Set correct permissions
RUN mkdir .next
RUN chown nextjs:nodejs .next

# Automatically leverage output traces to reduce image size
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

CMD ["node", "server.js"]
```

#### Development Dockerfile
```dockerfile
# syntax=docker/dockerfile:1

FROM node:20-alpine
WORKDIR /app

# Install dependencies for development
RUN apk add --no-cache libc6-compat python3 make g++

# Install dependencies first for better caching
COPY package.json package-lock.json* ./
RUN npm ci

# Copy the rest of the application
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
```

#### Docker Compose Configuration
```yaml
# docker-compose.yml
version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      # Add other environment variables as needed
    
  # Add other services as needed (e.g., database, cache)
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
```

#### Basic Setup
- [ ] Create production Dockerfile
- [ ] Create development Dockerfile
- [ ] Configure docker-compose.yml
- [ ] Set up .dockerignore file
- [ ] Configure environment variables

#### CI/CD Integration
- [ ] Create Docker build workflow
- [ ] Set up container registry
- [ ] Configure deployment pipeline
- [ ] Implement caching strategies

#### Optimization
- [ ] Implement multi-stage builds
- [ ] Optimize layer caching
- [ ] Minimize image size
- [ ] Configure resource limits

#### Documentation
- [ ] Development setup guide
- [ ] Production deployment guide
- [ ] Docker best practices
- [ ] Troubleshooting guide

### 3. Required Scripts

Add to package.json:
```json
{
  "scripts": {
    "docker:build": "docker build -t myapp .",
    "docker:dev": "docker-compose up",
    "docker:prod": "docker-compose -f docker-compose.prod.yml up",
    "docker:test": "docker-compose -f docker-compose.test.yml up",
    "docker:clean": "docker-compose down -v"
  }
}
```

### 4. .dockerignore Configuration
```plaintext
# .dockerignore
node_modules
.next
.git
.env*
.dockerignore
Dockerfile*
docker-compose*
README.md
.vscode
coverage
.github
test
*.log
```

### Development Environment
1. `docker-compose up` starts development environment
2. Hot reloading works correctly
3. Environment variables are properly handled
4. Volume mounts preserve local changes
5. Node modules are properly cached

### Production Environment
1. Multi-stage build optimizes image size
2. Production image is secure
3. Application runs with correct permissions
4. Environment variables are properly handled
5. Static assets are served correctly

### General Requirements
1. Images build successfully
2. Containers start without errors
3. Application is accessible on specified ports
4. Resource usage is optimized
5. Security best practices are followed

## Testing Requirements
- [ ] Test development environment setup
- [ ] Test production builds
- [ ] Verify hot reloading
- [ ] Check environment variable handling
- [ ] Test container networking
- [ ] Verify volume mounts
- [ ] Test CI/CD integration
- [ ] Performance testing
- [ ] Security scanning

### Security
- Use multi-stage builds
- Implement least privilege principle
- Scan for vulnerabilities
- Handle secrets securely
- Regular security updates

### Performance
- Optimize build times
- Minimize image sizes
- Implement layer caching
- Configure resource limits
- Monitor container health

### Monitoring
- Container health checks
- Resource usage monitoring
- Log aggregation
- Performance metrics
- Error tracking

## Resources
- [Docker Documentation](https://docs.docker.com/)
- [Next.js Deployment Documentation](https://nextjs.org/docs/deployment)
- [Docker Best Practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/)
- [Docker Compose Documentation](https://docs.docker.com/compose/)

## Related Issues
- #123 CI/CD Pipeline Implementation
- #124 Production Deployment Strategy
- #125 Container Monitoring Setup

## Time Estimate
- Basic setup: 4 hours
- Optimization: 4 hours
- Testing: 4 hours
- Documentation: 2 hours
- Total: ~14 hours

/cc @devops-team @security-team

---
Note: This implementation assumes basic familiarity with Docker and containerization concepts.
